# Generated by Django 5.0.14 on 2026-04-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
    ]
